#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/yaap/manifest.git -b eleven -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

git clone https://github.com/FrosT2k5/device_xiaomi_sakura device/xiaomi/sakura -b yaap --depth=1
git clone https://gitlab.com/FrosT2k5/vendor_xiaomi_sakura vendor/xiaomi --depth=1 -b wip 
git clone https://github.com/SuperCosmicBeing/kernel_xiaomi_sleepy kernel/xiaomi/msm8953 --depth=1
git clone https://github.com/kdrag0n/proton-clang --depth=1 prebuilts/clang/host/linux-x86/clang-proton

cd hardware/qcom-caf/
rm -rf wlan
git clone https://github.com/SuperCosmicBeing/hardware_qcom_wlan wlan/ --depth=1

cd msm8996
rm -rf display media audio
git clone https://github.com/SuperCosmicBeing/display --depth=1
git clone https://github.com/SuperCosmicBeing/media --depth=1
git clone https://github.com/SuperCosmicBeing/audio --depth=1
